version: "3"
services:  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
     - "8080:15672"
     - "5672:5672"
     - "25676:25676"
    networks:
      - back-tier

  metabase:
    image: metabase/metabase
    hostname: metabase
    ports:
      - "3000:3000"
    networks:
      - back-tier

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data 
    networks:
      - back-tier
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "vrezende@ext.vectoritcgroup.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - back-tier
  
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan
    networks:
      - back-tier

networks:
  back-tier:
    external:
      name: back-tier
